services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    ports:
      - 7575:7575
    networks:
      - caddy
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /srv/server/services/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=
    restart: unless-stopped

networks:
  caddy:
    name: caddy
    external: true