services:
  cloudflare_ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: cloudflare_ddns
    network_mode: host
    restart: always
    user: "1000:1000"
    cap_drop:
      - all
    read_only: true
    security_opt:
      - no-new-privileges:true
    environment:
      - CLOUDFLARE_API_TOKEN=YOUR_CLOUDFLARE_API_TOKEN
      - IP6_PROVIDER=none
      - DOMAINS=your-domain.tld,*.your-domain.tld,mc.your-domain.tld
      - CACHE_EXPIRATION=3h
      - TZ=Europe/Warsaw
      # - PROXIED=true
      - PROXIED=!is(mc.your-domain.tld)