services:
  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    depends_on:
      - database
      - redis
    volumes:
      - /srv/server/services/authelia/config:/config
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /config/secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /config/secrets/SESSION_SECRET
      AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE: /config/secrets/SMTP_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /config/secrets/STORAGE_ENCRYPTION_KEY
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /config/secrets/STORAGE_PASSWORD
      AUTHELIA_SESSION_REDIS_PASSWORD_FILE: /config/secrets/REDIS_PASSWORD
    networks:
      - authelia
      - caddy
  database:
    image: postgres:17
    container_name: authelia_db
    restart: unless-stopped
    volumes:
      - /srv/server/services/authelia/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "authelia"
      POSTGRES_PASSWORD: "STORAGE_PASSWORD"
    networks:
      - authelia
  redis:
    image: redis:7
    container_name: authelia_redis
    restart: unless-stopped
    command: "redis-server --save 60 1 --loglevel warning --requirepass REDIS_PASSWORD"
    volumes:
      - /srv/server/services/authelia/redis:/data
    networks:
      - authelia

networks:
  caddy:
    name: caddy
    external: true
  authelia:
    name: authelia