services:
  dashdot:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    ports:
      - 3001:3001
    privileged: true
    volumes:
      - /:/mnt/host:ro
    restart: unless-stopped