services:
  diun:
    image: crazymax/diun:latest
    container_name: diun
    command: serve
    volumes:
      - /srv/server/services/diun/data:/data
      - /srv/server/services/diun/diun.yml:/diun.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=Europe/Warsaw
      - LOG_LEVEL=info
      - LOG_JSON=false
    restart: unless-stopped