version: "3.8"

services:
  linkding:
    container_name: "${LD_CONTAINER_NAME:-linkding}"
    image: sissbruecker/linkding:latest
    ports:
      - "${LD_HOST_PORT:-9090}:9090"
    volumes:
      - "${LD_HOST_DATA_DIR:-/home/docker/linkding}:/etc/linkding/data"
    env_file:
      - stack.env
    restart: unless-stopped