services:
  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    ports:
      - 7575:7575
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /srv/server/services/homarr/configs:/app/data/configs
      - /srv/server/services/homarr/icons:/app/public/icons
      - /srv/server/services/homarr/data:/data
    restart: unless-stopped