services:
  caddy:
    image: serfriz/caddy-cloudflare-ddns-crowdsec-geoip-security:latest
    container_name: caddy
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80" # HTTP port
      - "443:443" # HTTPS port
      - "443:443/udp" # HTTP/3 port (optional)
    networks:
      - caddy
      - nextcloud-aio
    volumes:
      - /srv/server/services/caddy/data:/data
      - /srv/server/services/caddy/config:/config
      - /srv/server/services/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/server/services/caddy/logs:/var/log/caddy
    environment:
      - CLOUDFLARE_API_TOKEN=YOUR_CLOUDFLARE_API_TOKEN
      - ACME_AGREE=true
      - BASE_URL=your-domain.tld
    restart: unless-stopped

networks:
  caddy:
    name: caddy
    external: true
  nextcloud-aio:
    name: nextcloud-aio
    external: true