version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - /home/docker/portainer/data:/data
      - /home/docker/portainer/var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
volumes:
  data: