services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9443:9443
    volumes:
      - /srv/server/services/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped