services:
  rcon:
    container_name: rcon
    image: itzg/rcon
    ports:
      - 4326:4326
      - 4327:4327
    environment:
      RWA_USERNAME: "admin"
      RWA_PASSWORD: "changeme"
      RWA_ADMIN: true
      RWA_SERVER_NAME: "mc.your-domain.tld"
      RWA_RCON_HOST: mc
      RWA_RCON_PASSWORD: "changeme_rcon" # must be the same as in Minecraft server
    depends_on:
    - mc # we need to be sure that RCON web admin will be started after Minecraft server
    restart: unless-stopped
    volumes:
      - /srv/server/services/rcon:/opt/rcon-web-admin/db
  mc:
    container_name: mc
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    environment:
      # GENERAL
      MEMORY: "6G"
      MAX_MEMORY: "12G"
      TZ: "Europe/Warsaw"
      LOG_TIMESTAMP: true
      # SERVER
      TYPE: "FABRIC"
      EULA: true
      VERSION: "1.21"
      MOTD: "Motto of the day"
      DIFFICULTY: "normal"
      # ICON: "https://your-domain.tld/imgs/mc_icon.png"
      # OVERRIDE_ICON: true
      MAX_PLAYERS: 32
      ENABLE_COMMAND_BLOCK: true
      VIEW_DISTANCE: 16
      SERVER_NAME: "mc.your-domain.tld"
      EXEC_DIRECTLY: true
      ENABLE_QUERY: true
      # WHITELIST
      ENABLE_WHITELIST: true
      WHITELIST: "Steve,Alex"
      # RCON
      ENABLE_RCON: true
      RCON_PASSWORD: "changeme_rcon" # must be the same as in RCON web admin
    restart: unless-stopped
    volumes:
      - /srv/server/services/minecraft/servers/FABRIC_1_21:/data