services:
  linkwarden:
    image: ghcr.io/linkwarden/linkwarden:latest
    container_name: linkwarden
    environment:
      DATABASE_URL: "postgresql://linkwarden:POSTGRES_PASSWORD@linkwarden_db:5432/linkwarden_db"
      NEXTAUTH_SECRET: "SUPER_SECRET_WORLD"
      NEXTAUTH_URL: "https://linkwarden.your-domain.tld"
      # Uncomment this after you create your account(s)
      # NEXT_PUBLIC_DISABLE_REGISTRATION: true
    ports:
      - 3000:3000
    networks:
      - linkwarden
      - caddy
    depends_on:
      - linkwarden_db
    volumes:
      - /srv/server/services/linkwarden/data:/data/data
    restart: unless-stopped
  linkwarden_db:
    image: postgres:17
    container_name: linkwarden_db
    environment:
      POSTGRES_DB: "linkwarden_db"
      POSTGRES_PASSWORD: "POSTGRES_PASSWORD"
      POSTGRES_USER: "linkwarden"
    networks:
      - linkwarden
    volumes:
      - /srv/server/services/linkwarden/pgdata:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  caddy:
    name: caddy
    external: true
  linkwarden:
    name: linkwarden
    driver: bridge