services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    ports:
      - 5055:5055
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Warsaw
    volumes:
      - /srv/server/services/jellyseer/config:/app/config
    restart: unless-stopped