services:
  db:
    container_name: nextcloud_db
    image: mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW --character-set-server=utf8
    volumes:
      - /srv/server/services/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    restart: unless-stopped
  app:
    container_name: nextcloud
    image: nextcloud:latest
    ports:
      - 8080:80
    links:
      - db
    depends_on:
      - db
    volumes:
      - /srv/server/services/nextcloud/nc:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_PASSWORD=changeme
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
      - REDIS_HOST=nextcloud_cache
      - REDIS_PORT=6380
      - REDIS_HOST_PASSWORD=nextcloud_cache_password
    restart: unless-stopped
  redis:
    container_name: nextcloud_cache
    image: redis
    ports:
      - 6380:6379
    command: redis-server --requirepass nextcloud_cache_password
    restart: unless-stopped