services:
  mc:
    container_name: mc
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    environment:
      # GENERAL
      MEMORY: "6G"
      MAX_MEMORY: "12G"
      TZ: "Europe/Warsaw"
      LOG_TIMESTAMP: true
      # SERVER
      TYPE: "FABRIC"
      EULA: true
      VERSION: "1.21"
      MOTD: "Motto of the day"
      DIFFICULTY: "normal"
      # ICON: "url"
      # OVERRIDE_ICON: true
      MAX_PLAYERS: 32
      ENABLE_COMMAND_BLOCK: true
      VIEW_DISTANCE: 16
      SERVER_NAME: "server name"
      EXEC_DIRECTLY: true
      ENABLE_QUERY: true
      # WHITELIST
      ENABLE_WHITELIST: true
      WHITELIST: "Steve,Alex"
    restart: unless-stopped
    volumes:
      - /srv/server/services/minecraft/servers/FABRIC_1_21:/data