services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8096:8096
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - /srv/server/services/jellyfin/config:/config
      - /srv/server/media:/data
    restart: unless-stopped